name: Run Flop Labs Node v5

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-node-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js (Latest Version)
      uses: actions/setup-node@v4
      with:
        # تم التحديث إلى إصدار 24 المتوافق مع خوادم جيت هاب الجديدة لتفادي التحذير
        node-version: '24' 

    - name: Install Network Dependencies
      # أمر مضاف لتهيئة الحزم التلقائية قبل تشغيل ملف node.mjs
      run: npm install

    - name: Execute Node.mjs Script
      run: node node.mjs
      env:
        MY_SECRET_SEED: ${{ secrets.SECURITY_SEED }}
        NODE_MY_DID: "did:key:z6MkkC4yHPE3RJMkbSmwhYVPkrHSZ6XpCswccawJGLMwrLLQ"
