name: Run Flop Labs Node v5

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-node-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Execute Node.mjs Script
      run: node node.mjs
      env:
        # تم تعديل الاسم هنا ليقرأ من SECURITY_SEED  
        MY_SECRET_SEED: ${{ secrets.SECURITY_SEED }}
        NODE_MY_DID: "did:key:z6MkkC4yHPE3RJMkbSmwhYVPkrHSZ6XpCswccawJGLMwrLLQ"
